name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:                  
  group: ci-${{ github.ref }}
  cancel-in-progress: true    # :contentReference[oaicite:0]{index=0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4          
      - uses: actions/setup-python@v5      
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          uv sync --all-extras  # Install dev dependencies too
      - name: Run linting
        run: uv run ruff check .
      - name: Run formatting check
        run: uv run ruff format --check .
      - name: Run tests
        run: uv run pytest
      - name: Deploy
        run: curl -X POST -d '' https://kiisu.site:9000/hooks/deploy?secret=MY_SECRET
